const THEMES = {
  hxh: {
    name: 'Hunter × Hunter',
    cover: 'images/hxh/gon.png',
    color: 'hsl(0, 75%, 50%)',
    characters: [
      { id: 'gon', name: 'Gon Freecss', img: 'images/hxh/gon.png' },
      { id: 'killua', name: 'Killua Zoldyck', img: 'images/hxh/killua.jpg' },
      { id: 'kurapika', name: 'Kurapika', img: 'images/hxh/kurapika.jpg' },
      { id: 'leorio', name: 'Leorio Paladiknight', img: 'images/hxh/leorio.jpg' },
      { id: 'hisoka', name: 'Hisoka Morow', img: 'images/hxh/hisoka.jpg' },
      { id: 'chrollo', name: 'Chrollo Lucilfer', img: 'images/hxh/chrollo.jpg' },
      { id: 'meruem', name: 'Meruem', img: 'images/hxh/meruem.jpg' },
      { id: 'netero', name: 'Isaac Netero', img: 'images/hxh/netero.jpg' },
      { id: 'alluka', name: 'Alluka Zoldyck', img: 'images/hxh/alluka.webp' },
    ],
  },
  mha: {
    name: 'My Hero Academia',
    cover: 'images/mha/deku.jpg',
    color: 'hsl(38, 90%, 50%)',
    characters: [
      { id: 'deku', name: 'Izuku Midoriya', img: 'images/mha/deku.jpg' },
      { id: 'bakugo', name: 'Katsuki Bakugo', img: 'images/mha/bakugo.jpg' },
      { id: 'uraraka', name: 'Ochako Uraraka', img: 'images/mha/uraraka.png' },
      { id: 'todoroki', name: 'Shoto Todoroki', img: 'images/mha/todoroki.jpg' },
      { id: 'allmight', name: 'All Might', img: 'images/mha/allmight.jpg' },
      { id: 'iida', name: 'Tenya Iida', img: 'images/mha/iida.png' },
      { id: 'tsuyu', name: 'Tsuyu Asui', img: 'images/mha/tsuyu.jpg' },
      { id: 'kirishima', name: 'Eijiro Kirishima', img: 'images/mha/kirishima.jpg' },
    ],
  },
  onepiece: {
    name: 'One Piece',
    cover: 'images/onepiece/luffy.jpg',
    color: 'hsl(95, 60%, 45%)',
    characters: [
      { id: 'luffy', name: 'Monkey D. Luffy', img: 'images/onepiece/luffy.jpg' },
      { id: 'zoro', name: 'Roronoa Zoro', img: 'images/onepiece/zoro.jpg' },
      { id: 'nami', name: 'Nami', img: 'images/onepiece/nami.jpg' },
      { id: 'sanji', name: 'Sanji', img: 'images/onepiece/sanji.png' },
      { id: 'usopp', name: 'Usopp', img: 'images/onepiece/usopp.jpg' },
      { id: 'chopper', name: 'Tony Tony Chopper', img: 'images/onepiece/chopper.jpg' },
      { id: 'robin', name: 'Nico Robin', img: 'images/onepiece/robin.jpg' },
      { id: 'franky', name: 'Franky', img: 'images/onepiece/franky.jpg' },
    ],
  },
  naruto: {
    name: 'Naruto',
    cover: 'images/naruto/naruto.jpg',
    color: 'hsl(200, 70%, 45%)',
    characters: [
      { id: 'naruto', name: 'Naruto Uzumaki', img: 'images/naruto/naruto.jpg' },
      { id: 'sasuke', name: 'Sasuke Uchiha', img: 'images/naruto/sasuke.jpg' },
      { id: 'sakura', name: 'Sakura Haruno', img: 'images/naruto/sakura.jpg' },
      { id: 'kakashi', name: 'Kakashi Hatake', img: 'images/naruto/kakashi.jpg' },
      { id: 'itachi', name: 'Itachi Uchiha', img: 'images/naruto/itachi.jpg' },
      { id: 'gaara', name: 'Gaara', img: 'images/naruto/gaara.jpg' },
      { id: 'jiraiya', name: 'Jiraiya', img: 'images/naruto/jiraiya.jpg' },
      { id: 'rocklee', name: 'Rock Lee', img: 'images/naruto/rocklee.jpg' },
    ],
  },
  kuroko: {
    name: 'Kuroko\'s Basketball',
    cover: 'images/kuroko/kuroko.jpg',
    color: 'hsl(210, 15%, 55%)',
    characters: [
      { id: 'kuroko', name: 'Tetsuya Kuroko', img: 'images/kuroko/kuroko.jpg' },
      { id: 'kagami', name: 'Taiga Kagami', img: 'images/kuroko/kagami.jpg' },
      { id: 'kise', name: 'Ryota Kise', img: 'images/kuroko/kise.png' },
      { id: 'midorima', name: 'Shintaro Midorima', img: 'images/kuroko/midorima.jpg' },
      { id: 'aomine', name: 'Daiki Aomine', img: 'images/kuroko/aomine.jpg' },
      { id: 'murasakibara', name: 'Atsushi Murasakibara', img: 'images/kuroko/murasakibara.jpg' },
      { id: 'akashi', name: 'Seijuro Akashi', img: 'images/kuroko/akashi.jpg' },
      { id: 'momoi', name: 'Satsuki Momoi', img: 'images/kuroko/momoi.jpg' },
    ],
  },
  spyxfamily: {
    name: 'Spy × Family',
    cover: 'images/spyxfamily/anya.webp',
    color: 'hsl(325, 65%, 60%)',
    characters: [
      { id: 'anya', name: 'Anya Forger', img: 'images/spyxfamily/anya.webp' },
      { id: 'loid', name: 'Loid Forger', img: 'images/spyxfamily/loid.webp' },
      { id: 'yor', name: 'Yor Forger', img: 'images/spyxfamily/yor.webp' },
      { id: 'bond', name: 'Bond Forger', img: 'images/spyxfamily/bond.webp' },
      { id: 'franky', name: 'Franky Franklin', img: 'images/spyxfamily/franky.webp' },
      { id: 'yuri', name: 'Yuri Briar', img: 'images/spyxfamily/yuri.webp' },
      { id: 'damian', name: 'Damian Desmond', img: 'images/spyxfamily/damian.webp' },
      { id: 'fiona', name: 'Fiona Frost', img: 'images/spyxfamily/fiona.webp' },
    ],
  },
  demonslayer: {
    name: 'Demon Slayer',
    cover: 'images/demonslayer/tanjiro.webp',
    color: 'hsl(150, 55%, 35%)',
    characters: [
      { id: 'tanjiro', name: 'Tanjiro Kamado', img: 'images/demonslayer/tanjiro.webp' },
      { id: 'nezuko', name: 'Nezuko Kamado', img: 'images/demonslayer/nezuko.webp' },
      { id: 'zenitsu', name: 'Zenitsu Agatsuma', img: 'images/demonslayer/zenitsu.webp' },
      { id: 'inosuke', name: 'Inosuke Hashibira', img: 'images/demonslayer/inosuke.webp' },
      { id: 'giyu', name: 'Giyu Tomioka', img: 'images/demonslayer/giyu.webp' },
      { id: 'shinobu', name: 'Shinobu Kocho', img: 'images/demonslayer/shinobu.webp' },
      { id: 'rengoku', name: 'Kyojuro Rengoku', img: 'images/demonslayer/rengoku.webp' },
      { id: 'muzan', name: 'Muzan Kibutsuji', img: 'images/demonslayer/muzan.webp' },
      { id: 'muichiro', name: 'Muichiro Tokito', img: 'images/demonslayer/muichiro.webp' },
    ],
  },
  conan: {
    name: 'Detective Conan',
    cover: 'images/conan/conan.webp',
    color: 'hsl(260, 55%, 55%)',
    characters: [
      { id: 'conan', name: 'Conan Edogawa', img: 'images/conan/conan.webp' },
      { id: 'ran', name: 'Ran Mouri', img: 'images/conan/ran.webp' },
      { id: 'kogoro', name: 'Kogoro Mouri', img: 'images/conan/kogoro.webp' },
      { id: 'haibara', name: 'Ai Haibara', img: 'images/conan/haibara.webp' },
      { id: 'heiji', name: 'Heiji Hattori', img: 'images/conan/heiji.webp' },
      { id: 'kazuha', name: 'Kazuha Toyama', img: 'images/conan/kazuha.webp' },
      { id: 'sonoko', name: 'Sonoko Suzuki', img: 'images/conan/sonoko.webp' },
      { id: 'kaitokid', name: 'Kaito Kid', img: 'images/conan/kaitokid.webp' },
    ],
  },
};
